### PR TITLE
Dependency fix (MvDWPlaceholderAPI)

### PR DESCRIPTION
**Pull request by rocogamer**

### CODE REVIEW

**Comment by briannastatic** [comment]
Can you please explain what exactly this fixes?

**Comment by rocogamer** [comment]
Indicates the original source of the API MvDWPlaceHolderAPI.

Without that, if you don't have the API downloaded, compile fails

**Review by portlek — APPROVED** [review]
problem solved.

**Comment by SpraxDev** [comment]
Looks like `MVdWPlaceholderAPI` is no longer a dependency of FabledSkyBlock.

Sorry for this PR to be dead and never be merged - Thanks for your interests in contributing!

**Pull request closed without merging**
